from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
stm32f4xx_it.c
usart.c
spi.c
drv_hwtimer.c
sys.c
sdcard.c
timer.c
dac.c
""")

CPPPATH = [cwd]

src += Glob(cwd+'/rtc/*.c')
CPPPATH += [cwd + '/rtc/']

src += Glob(cwd+'/lcd/*.c')
CPPPATH += [cwd + '/lcd/']

src += Glob(cwd+'/sram/*.c')
CPPPATH += [cwd + '/sram/']

src += Glob(cwd+'/touch/*.c')
CPPPATH += [cwd + '/touch/']

# add Ethernet drivers.
if GetDepend('RT_USING_LWIP'):
    src += Glob(cwd + '/eth/*.c')

# add gpio drivers.
if GetDepend('RT_USING_PIN'):
    src += ['gpio.c']
    
# add sdio drivers.
if GetDepend('RT_USING_SDIO'):
    src += ['sdcard.c']
    
# addw25q16 drivers.
if GetDepend('RT_USING_W25QXX'):
    src += ['w25qxx.c']
	
if GetDepend('RT_USING_USB_DEVICE'):
	src += Glob(cwd+'/usbdevice/*.c')
	
if GetDepend('RT_MUSIC_SOFT_DECODE'):
	src += Glob(cwd+'/mp3/*.c')
	src += Glob(cwd+'/mp3/real/*.c')
	src += Glob(cwd+'/mp3/real/arm/*.s')
	CPPPATH += [cwd + '/mp3/']
	CPPPATH += [cwd + '/mp3/real/']
	CPPPATH += [cwd + '/mp3/pub/']
	
CPPPATH += [cwd + '/eth/']
CPPPATH += [cwd + '/../../../components/drivers/include/drivers/']
CPPPATH += [cwd + '/usbdevice/inc/']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
