# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('TEXT', src, depend = ['XQY_USING_TEXT'], CPPPATH = CPPPATH)

Return('group')
