# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('GUI', src, depend = ['XQY_USING_GUI'], CPPPATH = CPPPATH)

Return('group')
